on: [push]

name: Build head

jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustc -O build.rs
      - run: ./build
      - uses: actions/upload-artifact@v2
        with:
          name: bin-linux
          path: bin
  build-mac:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustc -O build.rs
      - run: ./build
      - uses: actions/upload-artifact@v2
        with:
          name: bin-macos
          path: bin
